font_size 12
font_family Jetbrains Mono Medium
bold_font Jetbrains Mono Bold
italic_font Cascadia Mono Italic
bold_italic_font Cascadia Mono Bold Italic
enable_audio_bell no
shell nu
confirm_os_window_close 0
foreground #C9C7CD
background #1B1B1C
color0 #131314
color8 #131314
color1 #EA83A5
color9 #EA83A5
color2 #90B99F
color10 #90B99F
color3 #E6B99D
color11 #E6B99D
color4 #92A2D5
color12 #92A2D5
color5 #E29ECA
color13 #E29ECA
color6 #85B5BA
color14 #85B5BA
color7 #C9C7CD
color15 #C9C7CD
map ctrl+v paste_from_clipboard
