set -gq @green "#90B99F"
set -gq @cyan "#85B5BA"
set -gq @blue "#92A2D5"
set -gq @violet "#ACA1CF"
set -gq @magenta "#E29ECA"
set -gq @red "#EA83A5"
set -gq @orange "#F5A191"
set -gq @yellow "#E6B99D"
set -gq @primary "#92A2D5"
set -gq @secondary "#E6B99D"
set -gq @active "#90B99F"
set -gq @pink "#E29ECA"
set -gq @aqua "#85B5BA"
set -gq @purple "#ACA1CF"
set -gq @brown "#F5A191"
set -gq @black "#131314"
set -gq @gray0 "#18181A"
set -gq @gray1 "#1B1B1C"
set -gq @gray2 "#2A2A2C"
set -gq @gray3 "#313134"
set -gq @gray4 "#3B3B3E"
set -gq @gray5 "#444448"
set -gq @gray6 "#6C6874"
set -gq @gray7 "#8B8693"
set -gq @gray8 "#9F9CA6"
set -gq @gray9 "#B4B1BA"
set -gq @white "#C9C7CD"
set -gq @foreground "#C9C7CD"
set -gq @background "#131314"
set -gq @bg0 "#18181A"
set -gq @bg1 "#1B1B1C"
set -gq @bg2 "#2A2A2C"
set -gq @bg3 "#313134"
set -gq @grey "#6C6874"
set -gq @green_25 "#363e39"
set -gq @green_50 "#526459"
set -gq @green_75 "#708e7b"
set -gq @cyan_25 "#333d3f"
set -gq @cyan_50 "#4d6265"
set -gq @cyan_75 "#698a8e"
set -gq @blue_25 "#363944"
set -gq @blue_50 "#535a71"
set -gq @blue_75 "#727da2"
set -gq @violet_25 "#3b3943"
set -gq @violet_50 "#5e5a6f"
set -gq @violet_75 "#847c9e"
set -gq @magenta_25 "#473942"
set -gq @magenta_50 "#77586d"
set -gq @magenta_75 "#ab7a9a"
set -gq @red_25 "#49333b"
set -gq @red_50 "#7b4d5c"
set -gq @red_75 "#b16880"
set -gq @orange_25 "#4b3936"
set -gq @orange_50 "#805a53"
set -gq @orange_75 "#b97d71"
set -gq @yellow_25 "#483e39"
set -gq @yellow_50 "#796458"
set -gq @yellow_75 "#ae8d7a"
set -gq @primary_25 "#363944"
set -gq @primary_50 "#535a71"
set -gq @primary_75 "#727da2"
set -gq @secondary_25 "#483e39"
set -gq @secondary_50 "#796458"
set -gq @secondary_75 "#ae8d7a"
set -gq @active_25 "#363e39"
set -gq @active_50 "#526459"
set -gq @active_75 "#708e7b"
set -gq @pink_25 "#473942"
set -gq @pink_50 "#77586d"
set -gq @pink_75 "#ab7a9a"
set -gq @aqua_25 "#333d3f"
set -gq @aqua_50 "#4d6265"
set -gq @aqua_75 "#698a8e"
set -gq @purple_25 "#3b3943"
set -gq @purple_50 "#5e5a6f"
set -gq @purple_75 "#847c9e"
set -gq @brown_25 "#4b3936"
set -gq @brown_50 "#805a53"
set -gq @brown_75 "#b97d71"