include-file = colors.ini

[bar/example]
width = 100%
height = 24pt
radius = 0

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.foreground}

font-0 = UbuntuMono Nerd Font:size=14

modules-left = xworkspaces 
modules-center = tray
modules-right = tmux docker filesystem backlight pulseaudio memory cpu temperature battery date 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
# wm-restack = i3
#
# override-redirect = true

[module/tray]
type = internal/tray

format-margin = 8pt
tray-spacing = 8pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.primary}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.red}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#E6B99D}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.red}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = " "
label-muted-foreground = ${colors.red}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "󰍛 "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "󰻠 "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date = %d-%m-%Y | %H:%M

label = %date%
label-foreground = ${colors.primary}

[module/backlight]
type = internal/backlight

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 98

format-charging = <animation-charging> <label-charging>
format-charging-underline = ${colors.primary}

format-discharging = <animation-discharging> <label-discharging>
format-discharging-underline = ${colors.secondary}

format-full-prefix = "󱈑 "
format-full-prefix-foreground = ${colors.green}
format-full-underline = ${colors.green}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-foreground = ${colors.foreground}

animation-charging-0 = 󰢜
animation-charging-1 = 󰂆
animation-charging-2 = 󰂇 
animation-charging-3 = 󰂈
animation-charging-4 = 󰢝
animation-charging-5 = 󰂉
animation-charging-6 = 󰂊
animation-charging-7 = 󰂋
animation-charging-8 = 󰂅

animation-charging-foreground = ${colors.foreground}
animation-charging-framerate = 250

animation-discharging-0 = 󰂂
animation-discharging-1 = 󰁿
animation-discharging-2 = 󰁾
animation-discharging-3 = 󰁼
animation-discharging-4 = 󰁺
animation-discharging-foreground = ${colors.secondary}
animation-discharging-framerate = 750

enable-scroll = true

[module/temperature]
type = internal/temperature
label = 󰻠 %temperature-c%
label-warn-foreground = ${colors.red}

[module/docker]
type = custom/script
exec = docker ps -q | wc -l
interval = 1
label = 󰡨 %output%

[module/tmux]
type = custom/script
exec = tmux list-panes -a | wc -l
interval = 1
label =  %output%

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
