require "user.launch"
require "user.options"
require "user.keymaps"
require "user.shortcuts.init"
require "user.autocmds"

spec "user.whichkey"

-- require "user.highlight"
-- require "user.watch"

-- spec "user.alpha"
-- spec "user.colorbuddy"
-- spec "user.debugprint"
-- spec "user.fantableous"
-- spec "user.fugitive"
-- spec "user.gitlab"
-- spec "user.hardtime"
-- spec "user.harpoon"
-- spec "user.headlines"
-- spec "user.hurl"
-- spec "user.image-preview"
-- spec "user.neotest"
-- spec "user.noice"
-- spec "user.notify"
-- spec "user.nvimtree"
-- spec "user.one-monokai"
-- spec "user.project"
-- spec "user.quickfix-reflector"
-- spec "user.rainbow-csv"
-- spec "user.remote-nvim"
-- spec "user.tailwind-sorter"
-- spec "user.tmux-navigator"
-- spec "user.treesitter"
-- spec "user.vim-be-good"
spec "user.oldworld"
spec "user.phpactor"
spec "user.workspace-diagnostics"
spec "user.auto-save"
spec "user.autopairs"
spec "user.blade"
spec "user.breadcrumbs"
spec "user.cmp"
spec "user.colorizer"
spec "user.colorscheme"
spec "user.comment"
spec "user.devicons"
spec "user.edgy"
spec "user.eunuch"
spec "user.extras.neoscroll"
spec "user.extras.oil"
spec "user.extras.ufo"
spec "user.fzf"
spec "user.gitsigns"
spec "user.illuminate"
spec "user.indentline"
spec "user.lsp-virtual-improved"
spec "user.lspconfig"
spec "user.lualine"
spec "user.markdown"
spec "user.mason"
spec "user.navic"
spec "user.neogit"
spec "user.neovim-tmux-navigator"
spec "user.none-ls"
spec "user.nu"
-- spec "user.nvimtree"
spec "user.outline"
spec "user.pkl"
spec "user.quicker"
spec "user.schemastore"
spec "user.spectre"
spec "user.surround"
spec "user.tailwind-tools"
spec "user.telescope"
spec "user.textobjs"
spec "user.toggleterm"
spec "user.trouble"

require "user.lazy"
