require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"
require "user.highlight"

-- spec "user.fugitive"
-- spec "user.harpoon"
-- spec "user.neotest"
-- spec "user.nvimtree"
-- spec "user.one-monokai"
-- spec "user.project"
-- spec "user.tmux-navigator"
spec "user.alpha"
spec "user.auto-save"
spec "user.autopairs"
spec "user.breadcrumbs"
spec "user.cmp"
spec "user.colorizer"
spec "user.colorscheme"
spec "user.comment"
spec "user.devicons"
spec "user.eunuch"
spec "user.extras.oil"
spec "user.extras.ufo"
spec "user.gitsigns"
spec "user.hurl"
spec "user.illuminate"
spec "user.indentline"
spec "user.lsp-virtual-improved"
spec "user.lspconfig"
spec "user.lualine"
spec "user.mason"
spec "user.navic"
spec "user.neogit"
spec "user.tmux-navigator"
spec "user.noice"
spec "user.none-ls"
spec "user.notify"
spec "user.nu"
spec "user.nvimtree"
spec "user.pkl"
spec "user.schemastore"
spec "user.surround"
spec "user.tailwind-sorter"
spec "user.telescope"
spec "user.toggleterm"
spec "user.treesitter"
spec "user.whichkey"

require "user.lazy"
